[project]
name = "onvif-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "onvif-zeep>=0.2.12",
    "uvicorn>=0.35.0",
]
